steps:
  # Step 1: Install Node.js dependencies
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Build the Angular application for production
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['run', 'build:prod']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rm', '-r', 'gs://battle-squire/public/*']

  # Step 3: Zip the build output
  - name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        zip -r dist.zip dist/tb/public
    dir: '.'

  # Step 4: Upload the zipped file to the Cloud Storage bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', 'dist.zip', 'gs://battle-squire/']
    dir: '.'

# Optional: Define substitution variables for flexibility
substitutions:
  _BUCKET_NAME: 'battle-squire'  # Replace with your bucket name
options:
  logging: CLOUD_LOGGING_ONLY
